### ISSUE TITLE
Composer failing for Nette 3

### ISSUE THREAD

**Issue by darkWolf-PR** [contributte/latte#21]
Hi, I´ve tried adding this component thinking about trying the latte email filter as it´s said for Nette 3 and PHP 7.2+, but composer is failing on this:

Using version ^0.4.1 for contributte/latte
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove nette/application v3.0.5
    - Conclusion: don't install nette/application v3.0.5
    - latte/latte v2.5.1 conflicts with nette/application[v3.0.5].
    - latte/latte v2.5.2 conflicts with nette/application[v3.0.5].
    - latte/latte v2.5.3 conflicts with nette/application[v3.0.5].
    - latte/latte v2.5.4 conflicts with nette/application[v3.0.5].
    - latte/latte v2.5.x-dev conflicts with nette/application[v3.0.5].
    - Installation request for nette/application (locked at v3.0.5, required as ^3.0) -> satisfiable by nette/application[v3.0.5].
    - Installation request for contributte/latte ^0.4.1 -> satisfiable by contributte/latte[v0.4.1].
    - Conclusion: don't install latte/latte v2.8.1|install latte/latte v2.5.1|install latte/latte v2.5.2|install latte/latte v2.5.3|install latte/latte v2.5.4|install latte/latte v2.5.x-dev
    - Conclusion: remove latte/latte v2.8.1|install latte/latte v2.5.1|install latte/latte v2.5.2|install latte/latte v2.5.3|install latte/latte v2.5.4|install latte/latte v2.5.x-dev
    - contributte/latte v0.4.1 requires latte/latte ~2.5.1|~2.6.0 -> satisfiable by latte/latte[v2.5.1, v2.5.2, v2.5.3, v2.5.4, v2.5.x-dev, v2.6.0, v2.6.1, v2.6.2, v2.6.x-dev].
    - Can only install one of: latte/latte[v2.6.0, v2.8.1].
    - Can only install one of: latte/latte[v2.6.1, v2.8.1].
    - Can only install one of: latte/latte[v2.6.2, v2.8.1].
    - Can only install one of: latte/latte[v2.6.x-dev, v2.8.1].
    - Installation request for latte/latte (locked at v2.8.1, required as ^2.5) -> satisfiable by latte/latte[v2.8.1].

I´m not exactly strong in composer rules...

**Comment by f3l1x** [comment]
Hey, show me your whole composer.json file.

**Comment by darkWolf-PR** [comment]
Base is Nette/web-project, stuff added by composer require...

```json
{
	"name": "nette/web-project",
	"description": "Nette: Standard Web Project",
	"keywords": ["nette"],
	"type": "project",
	"license": ["MIT", "BSD-3-Clause", "GPL-2.0", "GPL-3.0"],
	"require": {
		"php": ">= 7.2",
		"nette/application": "^3.0",
		"nette/bootstrap": "^3.0",
		"nette/caching": "^3.0",
		"nette/database": "^3.0",
		"nette/di": "^3.0",
		"nette/finder": "^2.5",
		"nette/forms": "^3.0",
		"nette/http": "^3.0",
		"nette/mail": "^3.0",
		"nette/robot-loader": "^3.0",
		"nette/security": "^3.0",
		"nette/utils": "^3.0",
		"latte/latte": "^2.5",
		"tracy/tracy": "^2.6",
		"ublaboo/datagrid": "^6.2",
		"ublaboo/datagrid-nette-database-data-source": "^2.0",
		"contributte/translation": "^0.6.1",
		"bicisteadm/webloader-reload": "^3.0",
		"scssphp/scssphp": "^1.0",
		"joseki/webloader-filters": "^1.1",
		"contributte/forms-bootstrap": "^0.2",
		"contributte/menu-control": "^2.2",
		"venca-x/nette-pagination": "dev-master",
		"ijvo/jquery-fileupload": "^2.1"
	},
	"require-dev": {
		"nette/tester": "^2.0",
		"phpstan/phpstan-nette": "^0.12"
	},
	"autoload": {
		"classmap": ["app/Bootstrap.php"]
	},
	"minimum-stability": "dev",
	"scripts": {
		"phpstan": "phpstan analyse --level 5 --configuration phpstan.neon app bin www"
	},
	"prefer-stable": true
}
```

**Comment by f3l1x** [comment]
This composer.json works.

```json
{
	"require": {
		"php": ">=7.1",
		"nette/application": "^3.0",
		"nette/bootstrap": "^3.0",
		"nette/caching": "^3.0",
		"nette/database": "^3.0",
		"nette/di": "^3.0",
		"nette/finder": "^2.5",
		"nette/forms": "^3.0",
		"nette/http": "^3.0",
		"nette/mail": "^3.0",
		"nette/robot-loader": "^3.0",
		"nette/safe-stream": "^2.4",
		"nette/security": "^3.0",
		"nette/utils": "^3.0",
		"latte/latte": "^2.5",
		"tracy/tracy": "^2.6",
		"contributte/latte": "^0.4.0"
	},
	"minimum-stability": "dev",
	"prefer-stable": true
}
```

Your composer.json works too.

```json
{
	"require": {
		"php": ">= 7.2",
		"nette/application": "^3.0",
		"nette/bootstrap": "^3.0",
		"nette/caching": "^3.0",
		"nette/database": "^3.0",
		"nette/di": "^3.0",
		"nette/finder": "^2.5",
		"nette/forms": "^3.0",
		"nette/http": "^3.0",
		"nette/mail": "^3.0",
		"nette/robot-loader": "^3.0",
		"nette/security": "^3.0",
		"nette/utils": "^3.0",
		"latte/latte": "^2.5",
		"tracy/tracy": "^2.6",
		"ublaboo/datagrid": "^6.2",
		"ublaboo/datagrid-nette-database-data-source": "^2.0",
		"contributte/translation": "^0.6.1",
		"bicisteadm/webloader-reload": "^3.0",
		"scssphp/scssphp": "^1.0",
		"joseki/webloader-filters": "^1.1",
		"contributte/forms-bootstrap": "^0.2",
		"contributte/menu-control": "^2.2",
		"venca-x/nette-pagination": "dev-master",
		"ijvo/jquery-fileupload": "^2.1",
		"contributte/latte": "^0.4.0"
	}
}
```
