### ISSUE TITLE
Move Symplify\ModularLatteFilters feature in here

### ISSUE THREAD

**Issue by TomasVotruba** [contributte/latte#9]
See https://github.com/Symplify/Symplify/issues/180

What do you think?

Let me know, if I shall prepare PR :+1:

**Comment by f3l1x** [comment]
Hi. I think we can merge it, it's basically only interface with getFilters method? I think it's not needed to create PR, I'll add it by my self.

**Comment by TomasVotruba** [comment]
Hey, thanks for response. Yep, that's it + load filters in beforeCompile() method.

I'm about to release Symplify 2.0 this, so it would be great if I could deprecate the package before release and point it here.

**Comment by TomasVotruba** [comment]
Symplify package deprecated via https://github.com/Symplify/Symplify/pull/186

**Comment by f3l1x** [comment]
I'll notice you when it'll be ready. Thanks.

**Comment by TomasVotruba** [comment]
Perfect! Thanks for making my life easier :)
